### ISSUE TITLE
Cant build model

### ISSUE THREAD

**Issue by hadaev8** [qhgz2013/anime-face-detector#1]
After !python setup.py build_ext --inplace
Get roor:
TypeError: can only concatenate list (not "dict") to list

Full code
https://colab.research.google.com/drive/1wLox24qohgrGiCr90gdnwRzQLZ54LGHY

**Comment by qhgz2013** [comment]
Fixed it in the newest commit, if something unexpected happen, try to run with argument `-nms-type PY_NMS` or open new issue.
