### ISSUE TITLE
Can I access to the training data?

### ISSUE THREAD

**Issue by yosuke-yasuda** [qhgz2013/anime-face-detector#2]
Hi! Thank you for creating great model.

Is it possible to access to the training data you used for this model? 
Guessing from the README, you prepared rough annotated data and adjusted the data manually. Is it right? It's ok to make such data by myself but it's very helpful if I can use existing data.

**Comment by qhgz2013** [comment]
Actually it is roughly labelled by myself in the spare time. I've temporarily uploaded the dataset archive on my google drive: [https://drive.google.com/open?id=1nDPimhiwbAWc2diok-6davhubNVe82pr](https://drive.google.com/open?id=1nDPimhiwbAWc2diok-6davhubNVe82pr) (Approx. 3GB)

The whole dataset structure is same as VOC2007. Just remind that commercial use is forbidden, original illustrators retain all the copyrights.
