### ISSUE TITLE
No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by anchpop** [qhgz2013/anime-face-detector#6]
I think this means you're still using tensorflow pre-2.0, how much trouble would it be to upgrade? I'll make a PR if you say it won't be too hard

**Comment by qhgz2013** [comment]
Actually I've planned it last year, and thought it's technically available after making a rough investigation, but lacking of time. Of course PRs are welcomed to make it compats with tf 1.x and 2.x
