### ISSUE TITLE
error: Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by Pxtri2156** [qhgz2013/anime-face-detector#7]
Hi everyone. I try to run the command "make". But I see the error: Unable to find vcvarsall.bat. 

Ps: I run it on Windows with anaconda 
Thanks

**Comment by qhgz2013** [comment]
Hmmm. Actually I'm using conda environment too, and the build process is passed from a clean clone of this repo. Maybe checking the environment or provide a detail information about it?  
The environment I use and test: anaconda 3, python 3.7, tensorflow 1.15.x, and VS 2019 (with c++ workload installed, it is necessary for building this extension).
Another option: adding argument `-nms-type=PY_NMS` to bypass this step.
